"""
Docstring for src.rag.document_store
vector database for news documents using Sentence Transformers + FAISS

News articles
     ↓
Split into chunks
     ↓
SentenceTransformer
     ↓
Text → embedding vector
     ↓
FAISS vector index
     ↓
Save index + metadata
     ↓
User query
     ↓
Query → embedding
     ↓
FAISS similarity search
     ↓
Most relevant news chunks
"""

import json

import pickle 
from pathlib import Path

import numpy as np
import faiss
from sentence_transformers import SentenceTransformer

INDEX_DIR = Path("data/cache/vector_store")
INDEX_DIR.mkdir(parents=True, exist_ok=True)

EMBEDDING_MODEL = "all-MiniLM-L6-v2"  # sentence transformer model


class DocumentStore:
    def __init__(self, name: str = "news_index"): #news_index-> default name
        self.name = name
        self.index_path = INDEX_DIR / f"{name}.faiss" #this is where the faiss will store actual vector index
        self.meta_path = INDEX_DIR / f"{name}_meta.pkl" #stores the metadata associated with each vector.
        # metadata list will contain the mapping of vector to its content.

        self.embedder = SentenceTransformer(EMBEDDING_MODEL) #loads embedding mmodel into the memory
        self.dim = self.embedder.get_embedding_dimension() #will return the length of the vector generated by embedding-model, ie 384

        self.index = faiss.IndexFlatIP(self.dim)  
        # this creates faiss index using inner product similarity
        """IP -> Inner Product -> A.B = summation(Ai. Bi)
            but since our code has normalize_embedding set as true -> this will generate normalised cosine similarity vector
            ie A.B = A.B. cos (theta)
        """
        self.metadata: list[dict] = []

        if self.index_path.exists():
            self._load()
        # loads new_index.faiss if it already exists

    def _load(self):
        self.index = faiss.read_index(str(self.index_path))
        with open(self.meta_path, "rb") as f:
            self.metadata = pickle.load(f)

    def _save(self):
        faiss.write_index(self.index, str(self.index_path))
        with open(self.meta_path, "wb") as f:
            pickle.dump(self.metadata, f)

    def add_documents(self, chunks: list[dict]):
       
        existing_ids = {m["chunk_id"] for m in self.metadata}
        # creates a set containing ids that are already stored.

        new_chunks = [c for c in chunks if c["chunk_id"] not in existing_ids]
        # this keeps only chunks that doesn't already exists -> idempotent ingestion, meaning if we run the add_document(chunk) twice, it will not add the chunks to the vectore store twice.
        if not new_chunks:
            return 0
        # if chunk already exists, no changes-> return 0_. 0 new documents added

        texts = [c["text"] for c in new_chunks] # extract text from the chunks
        embeddings = self.embedder.encode(texts, normalize_embeddings=True) # converts the text into embeddings by converting them to vectors
        # vectors have unit length, since normalised_embeddings = true, therefore cosine similarity search
        self.index.add(np.array(embeddings, dtype="float32")) # adding embeddings to faiss
        self.metadata.extend(new_chunks) # adding metadata
        self._save() # saves evrything, then writes to disk
        return len(new_chunks)

    def search(self, query: str, top_k: int = 5, ticker: str | None = None) -> list[dict]:
        """
        Returns the top_k most relevant chunks for `query`, optionally
        restricted to a single ticker. Each result includes a `score` field.
        """
        # ntotal tells how many vectors are there in the faiss
        if self.index.ntotal == 0:
            return []
        # faiss is empty-> there is nothing to search, then return an empty array

        query_vec = self.embedder.encode([query], normalize_embeddings=True)
        # converting query to embedding

        # Over-fetch when filtering by ticker so we still return top_k after filtering.
        fetch_k = top_k * 5 if ticker else top_k
        """
            ticker- short letter code used to idenntify companies in stock market
                eg) ticker for Apple is AAPL, Microsoft-> MSFT, TSLA for Tesla.

            If there is a ticker filter, over-fetch 5x as a buffer. 
            5 here is a heuristic, not a guarantee — it assumes on average at least 1-in-5 of the nearest neighbors will match your ticker. 
            If your vector store holds many tickers and one has very few articles, even top_k * 5 could still come up short, and search() would silently return fewer than top_k results.
        """

        # returns similarity score
        scores, indices = self.index.search(np.array(query_vec, dtype="float32"), fetch_k)

        results = []
        for score, idx in zip(scores[0], indices[0]):
            if idx == -1: # not enough result
                continue
            # ticker filtering
            """
                if we searched ticker = "AAPL", then only documents whose metadata contains ticker: AAPL are retrived.
                thus, a form of metadata filtering
            """
            doc = self.metadata[idx]
            if ticker and doc.get("ticker") != ticker:
                continue

            # appends similarity score
            results.append({**doc, "score": float(score)})
            if len(results) >= top_k: # stop after top_k
                break

        return results
